#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lex.yy.c" /*This file will be generated by the lex*/

typedef struct node
{
    char *name;
    struct node *next;
} node;

typedef node *symbolTable;

// To add the identifier in the symbol Table

symbolTable addtbl(symbolTable T, char *data, char* type)
{
    symbolTable temp = T;
    while (temp)
    {
        if (!strcmp(temp->name, data))
        {
			printf("______________________________________________\n");
            printf("%s: {%s} is already present\n", type, data);
			printf("______________________________________________\n");
            return T;
        }
        temp = temp->next;
    }
    // else add it to the front of the linked list
    temp = (symbolTable)malloc(sizeof(node));
    temp->name = (char *)malloc(strlen(data) + 1);
    strcpy(temp->name, data);
    temp->next = T;
    T = temp;
    // print the message
	printf("______________________________________________\n");
    printf("\n%s: {%s} is added to the Symbol Table\n\n",  type,data);
	printf("______________________________________________\n\n");
    return T;
}

// print symbolTable for the identifiers
void print(symbolTable T, char* type)
{
    symbolTable temp = T;
    while (temp)
    {
        printf("%s: %s\n", type, temp->name);
        temp = temp->next;
    }
    printf("\n");
}

int main()
{
    int nextToken;
    symbolTable identifier_symbol_table = NULL;
    symbolTable number_symbol_table = NULL;
    while ((nextToken = yylex()))
    {
        switch (nextToken)
        {
        case KEYWORD:
            printf("<KEYWORD, %s>\n", yytext);
            break;
        case IDENTIFIER:
            printf("<Identifiers, %s>\n", yytext);
            // add the identifier to the symbol Table
            identifier_symbol_table = addtbl(identifier_symbol_table, yytext, "Identifier");
            break;
        case INTEGER_CONST:
            printf("<Integer constant, %s>\n", yytext);
            // add the number to the symbol Table
            number_symbol_table = addtbl(number_symbol_table, yytext, "Number");
            break;
        case FLOAT_CONST:
            printf("<Floating constant, %s>\n", yytext);
            // add the number to the symbol Table
            number_symbol_table = addtbl(number_symbol_table, yytext, "Number");
            break;
        case CHAR_CONST:
            printf("<char constant, %s>\n", yytext);
            break;
        case STRING_LITERAL:
            printf("<string literal, %s>\n", yytext);
            break;
        case PUNCTUATOR:
            printf("<punctuator, %s>\n", yytext);
            break;
        case MULTI_LINE_COMMENT:
            printf("<Multi line comment: %s>\n", yytext);
            break;
        case SINGLE_LINE_COMMENT:
            printf("<Single line comment: %s>\n", yytext);
            break;
        case WHITESPACE:
            // ignore whitespaces
            break;
        case MULTI_LINE_COMMENT_END:
            printf("Multi line comment end token (*/) recognized without its prior start token (/*)\n");
            break;
        case INVALID_CHAR_CONST:
            printf("Invalid char constant:  %s\n", yytext);
            break;
        case INVALID_STRING:
            printf("Invalid string: %s\n", yytext);
            break;
        case INVALID_SINGLE_CHAR:
            printf("Invalid token:  %s\n", yytext);
            break;
        case BRFV_ESCAPE:
            // ignore \b \r \f \v
            break;
        default:
            printf("Unrecognized token\n");
            break;
        }
    }

    printf("\n");
    printf("*******************Identifier Symbol Table*******************\n");
    print(identifier_symbol_table, "Id");
    printf("*********************Number Symbol Table*********************\n");
    print(number_symbol_table, "Num");
    return 0;
}